name: Build APK

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Restore cached libtun2socks
      id: cache-libtun2socks-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/libs
        key: libtun2socks-${{ runner.os }}-${{ hashFiles('.git/modules/badvpn/HEAD') }}-${{ hashFiles('.git/modules/libancillary/HEAD') }}

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      # Same version as https://gitlab.com/fdroid/fdroiddata/metadata/com.v2ray.ang.yml
      with:
        ndk-version: r27
        add-to-path: true
        link-to-sdk: true
        local-cache: true

    - name: Restore Android Symlinks
      run: |
        directory="${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin"
        find "$directory" -type l | while read link; do
            current_target=$(readlink "$link")
            new_target="$directory/$(basename "$current_target")"
            ln -sf "$new_target" "$link"
            echo "Changed $(basename "$link") from $current_target to $new_target"
        done

    - name: Build libtun2socks
      if: steps.cache-libtun2socks-restore.outputs.cache-hit != 'true'
      run: |
        bash compile-tun2socks.sh
        tar -xvzf libtun2socks.so.tgz
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Save libtun2socks
      if: steps.cache-libtun2socks-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/libs
        key: libtun2socks-${{ runner.os }}-${{ hashFiles('.git/modules/badvpn/HEAD') }}-${{ hashFiles('.git/modules/libancillary/HEAD') }}

    - name: Copy libtun2socks
      run: |
        cp -r ${{ github.workspace }}/libs ${{ github.workspace }}/V2rayNG/app

    - name: Fetch AndroidLibXrayLite tag
      run: |
        pushd AndroidLibXrayLite
        CURRENT_TAG=$(git describe --tags --abbrev=0)
        echo "Current tag in this repo: $CURRENT_TAG"
        echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_ENV
        popd

    - name: Download libv2ray
      uses: robinraju/release-downloader@v1
      with:
        repository: '2dust/AndroidLibXrayLite'
        tag: ${{ env.CURRENT_TAG }}
        fileName: 'libv2ray.aar'
        out-file-path: V2rayNG/app/libs/

    - name: Restore cached libhysteria2
      id: cache-libhysteria2-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/hysteria/libs
        key: libhysteria2-${{ runner.os }}-${{ hashFiles('.git/modules/hysteria/HEAD') }}-${{ hashFiles('libhysteria2.sh') }}

    - name: Setup Golang
      if: steps.cache-libhysteria2-restore.outputs.cache-hit != 'true'
      uses: actions/setup-go@v5
      with:
        go-version-file: 'AndroidLibXrayLite/go.mod'

    - name: Build libhysteria2
      if: steps.cache-libhysteria2-restore.outputs.cache-hit != 'true'
      run: |
        bash libhysteria2.sh
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Save libhysteria2
      if: steps.cache-libhysteria2-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/hysteria/libs
        key: libhysteria2-${{ runner.os }}-${{ hashFiles('.git/modules/hysteria/HEAD') }}-${{ hashFiles('libhysteria2.sh') }}

    - name: Copy libhysteria2
      run: |
        cp -r ${{ github.workspace }}/hysteria/libs ${{ github.workspace }}/V2rayNG/app

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android environment
      uses: android-actions/setup-android@v3

    - name: Decode Keystore
      uses: timheuer/base64-to-file@v1
      id: android_keystore
      with:
        fileName: "android_keystore.jks"
        path: ${{ github.workspace }}/V2rayNG/android_keystore.jks
        # encodedString: ${{ secrets.APP_KEYSTORE_BASE64 }}
        encodedString: MIIKtgIBAzCCCmAGCSqGSIb3DQEHAaCCClEEggpNMIIKSTCCBbAGCSqGSIb3DQEHAaCCBaEEggWdMIIFmTCCBZUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFJ4nbtk92jWPgPmQ1hJkS7HLbYDOAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQuyASYH8tngDChjqCD5rIAQSCBNCH3EkUpdLZz2uf2i1qkit+AKx+LEUPNaedC2g6+BYiMdQymBZeKrBuaBKGs+nCGtm5Q2ruKOJz8AjpCBdoUw1TFgtTu6vgiQDZaMP3SxseLPZXxlTxBbdjQlIjxJhKeZg/ax2gN9TDCZ3z6YAI+IWV80cyF36I7ZKFVF0RSpygIT7p4WMh7aFr81j0pCT2mNiENByWXiO2bQ96l3qAzcOgwo9lH+N0p6QiDYuHHdkGtVoI7FrKaFS80hIXomh8hCvOQHVjU/b/gcyQOHm7dNJm9smDEwuzS5ulU0OB5PNvLl0MX3zmtTQgPQ7Id75roBz5xxYc4hU85WUOUNadTXLv92VVYU6QfYFGDKrUYu4hr0aG19wSVSzmI16jjHqrHCSFXIh1hZJMcSkmp1+O9TKXhmxnqZ9d6u95N+72Pi6c9iyRsEGDqaGu1J/K1mNcsC62RH9ZAzVYMUP1Pn7/pA7PVuDpcW8+j8ne9hXQ1zVWmhYCu0YNPeLCj0CrTepGn0njntt6WmcEoeFravJOm8wH++ovw61EjKD4PZQuQOD/oJOXnY9y4zhXdpaaOePixEjoeedOOymjiMFMDUUOlYy4YqiAFOkfhhkGLqbCN4DaTLPkcRRFMAR1xGbe7ZsCQ4fOZ8DBWeGc9k7R+itqAgidg8PL0Acfd+/QklCRDwQ1VwzML4PGN08BwjVNNf5V0Nybpn1V6hY88DbTyzZQYROrdO4HUetfJWOjMh820teA4+uf5OVPvvNhUJYVfJl0K7R7ivYLwRNkY49u9jEzR4wV9HnRNGHInxnuhpoMgh1pWxLXnKIXzQwwx7MslkLSwsGbZAYbaRWdWYc4WVrGmN10pRsU0mKOd+jkeWV3tGZCLXNNNWqmxxfCHnSxOe1XkCIyg79WEgEbCZYqzXENMmU2DeiGcYO+wikP+qIZQRsbxMQrZloBUbx8Nnh0vOawLCtixiAsgd/vyXua0hIyFWXdNphWIzuhXqhGdZN3NDy11p7ZBeTMVs8tFvrxM9VFH4voDzcl5dTAJc5jhhb4FSQL1YbmlcYtqLpncHh8AJVJ/dyMB+qps08yyTP7xv9z9MR/S+KCQ3p24fB+/uBx7RI8HorC0SFs5RAajJUUOnkK7SehRkSSimUnVCFgG4AmgN1EvkxsS7KqVmyOZGOmO2dWbAIIea+lFjNt8EfQiXpw8JwqKsxXuSyaf+pkpcRa8dDGjhgN+gOLel3x0JB29h66tVrxdDQP6ROBcW63OtGfqv209JDgoYIZxzX9D7y2snIOwKXJEGhjAujPc9t47IxE9WbwxREpgT/fBs7bfX+KTQ4joL/drgUh8aLREJe3YkrMKQ3ZFniNkYzL9NWmtvJgCC8f1AXi9Zft8QewyNEjutHal5WY3BpihB8/uQr07hF0vkICjb/HXkWrfPAlDG+pNbqhwrqnHvqRVamAIPXquYj09Pob51lN72oVhYzUtQ5knKRJ6UBUY2DOLsHnSDwTpMpupGoNfDeDY1iinfKrsRdEbV4ua6nTxlTyUQoMwwNWz30jCfjsOZJnF1oys2OBlCdA7ohsa7v3zOpbxJpC4Vk6y5iwZbNo9USpd79oO7etsBFSWoc2RcbpbZczZ6aKgTsHNXYy+Qsp7SdiCQTYsTFCMB0GCSqGSIb3DQEJFDEQHg4AbAB1AG4AYQBzAGUAYTAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNzQwMTA2NzU2Nzg3MIIEkQYJKoZIhvcNAQcGoIIEgjCCBH4CAQAwggR3BgkqhkiG9w0BBwEwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFF5QKo/sKtCcBZibn8jQ+GYpr/dFAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ3B/nwWon0PDCBonkY8p/zoCCBADOHHNu+7UQ87Dujv4L+GaXR4RMImTQ9jgz38nweHvmtRP70B0ihwnD4TgnOLltN78X83L3DJoT9uPDc52kgdvtfdEb+bGOH4Ds8LhjFLxRVbvdqCurzci0Qkv7gxKNCRpcb/j+1PAfTWmafOSdw619spUJhW679Sb0/D3x4JFhZ7yHUxbM/AKAiBYz53MM+JIi8AHnw/V/G7zmopJuVCExR7gLEbtshcV4vUhZ+faJ2456gVLetj5rCNhiSlI2gVA3OEc5kMTWJ6Up/jdmvaYbThGqkgi5bJiNh0qTo8IO6ixq9oUE+qWokD5Ls1jB+T+eLc7yZKxrrFTw7x2dR3dT+UehYNKz5fHq8MP5kDCCBetghy7jINq1RZe458BV2pWClaNPjWlPuFIvZMlLqWM0j3f4JA0HYosLIu4pDw8iNsQSMTUWc6fq9bZP7ZiSth9CXTgpRe5gqye6zEUEVztKjte0Z7hF/05z+LWuHKiQO91d1FZ5V6wueVXMg5x87hyDrESaxe0ciTmgExqkNc9DDhDT7OigCsLWanGoBm2now8DO/1pcQ7KrlofIAIEgc+QtIDheAJA7FmpVR7LjbPgYxB0EUe3TlELhS/QSVPuPg8vpYfBzb121H1htWoUm3yGR1oSscmWwpDyQG984uBu/vABDCZP4z6dqFcGvkr89og8RN352sDA1CAkI30ToCcunP5XC9U0A6RH9zklooGCO2vh7xhjKoFn2palkBARDvqMFYL9eLKPO/feorL4Bg41qKK4+0jNkNv2uWEI4W4342FbdftyRnVyCMYn8De7rOzJgzu61d9CFb5+NRYueClGIYiIWMzKkfsC7MaMM4JJJMmgxytuoQN38kgJ5sJwva9iGzQ6B6ndpnK6EnEvBYazR54WkK4D6aRi0pdPClMHdXr1iun26Ee6pUFMbFR2P8AQPmqAKDFKehIUWee2cx8N/Xv27ZYtUkoWonVhiqIJbd21RRIFVrBRh47LDBAXvB4Ov/kF64pxmfz3VX+A0W1WsmJqy03ZSeI3aRymx/DlwO9oHgPCS5+WwJMsiWhPEViBQhLIyqqsZk6Xg3S5rrhn9uJZr2nV5ll3/fQXtWwtjhzdb/1PgagQBhx2ALrTMrhsqtxwFpq1zXi/g/kwj8NA5iOYei2ggrXh5ydDo7eODb4zzIWSlqVOWpPbCTKlieaYxHrZlVrDzXmeoG4d4mpQNNX+4MDVTCcx5Cvs8uWwfh6NMadeTwEG07oQJwGAI1E+rLeezlD20lwaA6QzYLyRBD3JiJXnXHwVNs4ssjUlL9RnRiFevkxr/HKe17qQDOEB6RlTTWbTuXvvH21Je3y9PhcyAW4q2nctnnrDlOXYME0wMTANBglghkgBZQMEAgEFAAQger2GE+xhXlV0qnkYxKG5rvfOnMfVRo3T+/FMUvwrOmgEFCq82x0CUcmcuThhzXZq2mUHTN+HAgInEA==

    - name: Build APK
      run: |
        cd ${{ github.workspace }}/V2rayNG
        chmod 755 gradlew
        ./gradlew licenseFdroidReleaseReport
        ./gradlew assembleRelease -Pandroid.injected.signing.store.file=android_keystore.jks -Pandroid.injected.signing.store.password=123456 -Pandroid.injected.signing.key.alias=lunasea -Pandroid.injected.signing.key.password=123456
        

        
    ##  ./gradlew assembleRelease -Pandroid.injected.signing.store.file=${{ steps.android_keystore.outputs.filePath }} -Pandroid.injected.signing.store.password=${{ secrets.APP_KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.APP_KEYSTORE_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.APP_KEY_PASSWORD }}   
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Upload arm64-v8a APK
      uses: actions/upload-artifact@v4
      if: ${{  success() }}
      with:
        name: arm64-v8a
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*arm64-v8a*.apk

    - name: Upload armeabi-v7a APK
      uses: actions/upload-artifact@v4
      if: ${{  success() }}
      with:
        name: armeabi-v7a
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*armeabi-v7a*.apk

    - name: Upload x86 APK
      uses: actions/upload-artifact@v4
      if: ${{  success() }}
      with:
        name: x86-apk
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*x86*.apk

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      if: github.event.inputs.release_tag != ''
      with:
        file: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*playstore*/release/*.apk
        tag: ${{ github.event.inputs.release_tag }}
        file_glob: true
        prerelease: true
